version: "3"
services:
  postgresql:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'zipline']
      interval: 10s
      timeout: 5s
      retries: 5

  zipline:
    image: ghcr.io/diced/zipline:latest
    restart: unless-stopped
    environment:
      - CORE_SECRET=${ZIPLINE_SECRET}
      - CORE_HOSTNAME=0.0.0.0
      - CORE_PORT=${ZIPLINE_PORT}
      - DATABASE_URL=postgres://postgres:postgres@postgres/postgres
      - DATASOURCE_TYPE=local
      - DATASOURCE_LOCAL_DIRECTORY=./uploads
    volumes:
      - './uploads:/zipline/uploads'
      - './public:/zipline/public'
      - './themes:/zipline/themes'
    depends_on:
      postgresql:
        condition: service_healthy

volumes:
  pgdata:
